esphome:
  name: novelkey2

esp8266:
  board: esp12e

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

dashboard_import:
  package_import_url: github://AeroSteveO/EspDeck/main/novelkey-big-switch/big-switch-keypad.yaml

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Novelkey2 Fallback Hotspot"
    password: "bigLongUniqueString"

captive_portal:


switch:
  - platform: gpio
    pin: 16
    id: red
    name: "Novelkey 1 Red"
    restore_mode: RESTORE_DEFAULT_OFF
    interlock: [blue,green]
  - platform: gpio
    pin: 5
    id: green
    name: "Novelkey 1 Green"
    restore_mode: RESTORE_DEFAULT_OFF
    interlock: [blue,red]
  - platform: gpio
    pin: 4
    id: blue
    name: "Novelkey 1 Blue"
    restore_mode: RESTORE_DEFAULT_OFF
    interlock: [red,green]
  - platform: gpio
    pin: 0
    id: red2
    name: "Novelkey 2 Red"
    restore_mode: RESTORE_DEFAULT_OFF
    interlock: [blue2,green2]
  - platform: gpio
    pin: 2
    id: green2
    name: "Novelkey 2 Green"
    restore_mode: RESTORE_DEFAULT_OFF
    interlock: [blue2,red2]
  - platform: gpio
    pin: 14
    id: blue2
    name: "Novelkey 2 Blue"
    restore_mode: RESTORE_DEFAULT_OFF
    interlock: [red2,green2]
binary_sensor:
  - platform: gpio
    pin:
      number: 12
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Novelkey Switch 1"


  - platform: gpio
    pin:
      number: 13
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Novelkey Switch 2"
    
- platform: status
    name: "Keypad Status"

